apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: productapp

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - networkpolicy.yaml

commonLabels:
  app: productapp
  managed-by: kustomize

images:
  - name: productapp
    newName: productapp
    newTag: latest
